/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b37a9bb9-b97f-4909-ae41-acf401a8a6ef",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_r3Z2yV5nH",
    "aws_user_pools_web_client_id": "66lupt3hubi3cjufu9e7s2h31b",
    "oauth": {}
};


export default awsmobile;
